# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import messages_pb2 as messages__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in messages_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WorkerServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ping = channel.unary_unary(
                '/scheduler.WorkerService/Ping',
                request_serializer=messages__pb2.PingRequest.SerializeToString,
                response_deserializer=messages__pb2.PingResponse.FromString,
                _registered_method=True)
        self.MeasureLink = channel.unary_unary(
                '/scheduler.WorkerService/MeasureLink',
                request_serializer=messages__pb2.LinkRequest.SerializeToString,
                response_deserializer=messages__pb2.LinkResponse.FromString,
                _registered_method=True)
        self.ProfileTask = channel.unary_unary(
                '/scheduler.WorkerService/ProfileTask',
                request_serializer=messages__pb2.TaskProfileRequest.SerializeToString,
                response_deserializer=messages__pb2.TaskProfileResponse.FromString,
                _registered_method=True)
        self.ExecuteTask = channel.unary_unary(
                '/scheduler.WorkerService/ExecuteTask',
                request_serializer=messages__pb2.ExecuteTaskRequest.SerializeToString,
                response_deserializer=messages__pb2.ExecuteTaskResponse.FromString,
                _registered_method=True)


class WorkerServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Ping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MeasureLink(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProfileTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=messages__pb2.PingRequest.FromString,
                    response_serializer=messages__pb2.PingResponse.SerializeToString,
            ),
            'MeasureLink': grpc.unary_unary_rpc_method_handler(
                    servicer.MeasureLink,
                    request_deserializer=messages__pb2.LinkRequest.FromString,
                    response_serializer=messages__pb2.LinkResponse.SerializeToString,
            ),
            'ProfileTask': grpc.unary_unary_rpc_method_handler(
                    servicer.ProfileTask,
                    request_deserializer=messages__pb2.TaskProfileRequest.FromString,
                    response_serializer=messages__pb2.TaskProfileResponse.SerializeToString,
            ),
            'ExecuteTask': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteTask,
                    request_deserializer=messages__pb2.ExecuteTaskRequest.FromString,
                    response_serializer=messages__pb2.ExecuteTaskResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'scheduler.WorkerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('scheduler.WorkerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WorkerService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scheduler.WorkerService/Ping',
            messages__pb2.PingRequest.SerializeToString,
            messages__pb2.PingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MeasureLink(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scheduler.WorkerService/MeasureLink',
            messages__pb2.LinkRequest.SerializeToString,
            messages__pb2.LinkResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProfileTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scheduler.WorkerService/ProfileTask',
            messages__pb2.TaskProfileRequest.SerializeToString,
            messages__pb2.TaskProfileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scheduler.WorkerService/ExecuteTask',
            messages__pb2.ExecuteTaskRequest.SerializeToString,
            messages__pb2.ExecuteTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
