task_types:
  capture:
    rpi01:
      mean_ms: 192.63
      min_ms: 136.7
      max_ms: 675.05
    laptop01:
      mean_ms: 112.58
      min_ms: 108.57
      max_ms: 117.86
  preprocess:
    rpi01:
      mean_ms: 849.16
      min_ms: 632.85
      max_ms: 2737.72
    laptop01:
      mean_ms: 344.84
      min_ms: 327.47
      max_ms: 378.88
  detect_person:
    rpi01:
      mean_ms: 1400.51
      min_ms: 1343.71
      max_ms: 1822.43
    laptop01:
      mean_ms: 509.81
      min_ms: 492.72
      max_ms: 605.41
  detect_helmet:
    rpi01:
      mean_ms: 1347.77
      min_ms: 1305.59
      max_ms: 1670.2
    laptop01:
      mean_ms: 494.66
      min_ms: 481.43
      max_ms: 543.45
  decide:
    rpi01:
      mean_ms: 124.93
      min_ms: 123.73
      max_ms: 128.36
    laptop01:
      mean_ms: 115.81
      min_ms: 111.25
      max_ms: 137.67
