task_types:
  capture:
    rpi01:
      mean_ms: 2117.15
      min_ms: 2098.28
      max_ms: 2143.91
    laptop01:
      mean_ms: 2096.5
      min_ms: 2090.39
      max_ms: 2118.2
    jetson01:
      mean_ms: 2141.64
      min_ms: 2140.31
      max_ms: 2143.61
  preprocess:
    rpi01:
      mean_ms: 3125.52
      min_ms: 3110.66
      max_ms: 3150.37
    laptop01:
      mean_ms: 3096.2
      min_ms: 3090.26
      max_ms: 9999
    jetson01:
      mean_ms: 3142.04
      min_ms: 3140.68
      max_ms: 3144.17
  detect:
    rpi01:
      mean_ms: 4123.94
      min_ms: 4110.22
      max_ms: 4142.33
    laptop01:
      mean_ms: 4098.05
      min_ms: 4091.6
      max_ms: 4112.95
    jetson01:
      mean_ms: 4144.3
      min_ms: 4142.05
      max_ms: 4146.46
  log:
    rpi01:
      mean_ms: 1108.29
      min_ms: 1097.73
      max_ms: 1140.11
    laptop01:
      mean_ms: 1099.59
      min_ms: 1091.29
      max_ms: 1111.63
    jetson01:
      mean_ms: 1141.25
      min_ms: 1140.69
      max_ms: 1142.79
