links:
  rpi01:
    laptop01:
      latency_ms: 1.86
      bandwidth_mbps: 940.62
    jetson01:
      latency_ms: 0.52
      bandwidth_mbps: 940.22
  laptop01:
    rpi01:
      latency_ms: 1.0
      bandwidth_mbps: 948.69
    jetson01:
      latency_ms: 1.0
      bandwidth_mbps: 950.1
  jetson01:
    rpi01:
      latency_ms: 0.39
      bandwidth_mbps: 941.25
    laptop01:
      latency_ms: 1.63
      bandwidth_mbps: 940.31
